### ISSUE TITLE
Z+ button mislabeled (jog screen)

### ISSUE THREAD

**Issue by JeffCalwood** [twentyfortysix/uccnc_screenset_2046#2]
The button caption is incorrectly 'Z-'.

**Comment by twentyfortysix** [comment]
I basically never use the jog screen ;)
Will check that once I'll be on machine and fix it.
Thanks for the feedback.

**Comment by twentyfortysix** [comment]
z+off@2x_2.png and z+on@2x_2.png icons fixed to "+Z"
see https://github.com/twentyfortysix/uccnc_screenset_2046/tree/main/UCCNC/Flashscreen/BMP/Stepcraft_2046
If you re-download these to your UCCNC/Flashscreen/BMP/Stepcraft_2046 you should be fine.

**Comment by JeffCalwood** [comment]
Thanks for the fix and your screenset in general. Should be the standard UCCNC screenset IMHO.
