### ISSUE TITLE
Missing folder in BMP

### ISSUE THREAD

**Issue by rtm729** [twentyfortysix/uccnc_screenset_2046#3]
Seems the image folder in Flashscreen/BMP is missing for the  BMP/Probe/    When you go to probe tab most of it is blank.
This may be a standard folder for stepcraft machines but isn't for clean install. Could you add this to the files?

**Comment by twentyfortysix** [comment]
Where the screenset does not use it's own graphics it refers back the UCCNC default files (not Stepcraft default files).

The last time I have seen the probe with white images was when I tried the new version UCCNC v1.2116 where the file structure might have changed. I have not updated the Screenset for this version yet, as when I tried the v1.2116 my Stepcraft just gave up.
see https://www.forum.cncdrive.com/viewtopic.php?f=3&t=4623
I don't know on what version you are and on what machine you are.
But if you are on Stepcraft I recommend to stay with the v1.2115 until we have referential screenset for this new version I can expand on. Maybe in general it is good to stay on the v1.2115, until the new version is really safe.
_(There is lot of new things in v1.2116 the Screenset is not aware of yet.)_

If you are on the v1.2115 or less and do not see the probe images it is different story and in that case you might be disappointed, as I have not redesigned the probe screen in my Screenset at all, and it is a bit of mess even on v1.2115.

I do not think the default files should be part of my Screenset and so I will not make it part of the shared code.
I can upload the images to somewhere and send you a link if you want me to, but I just want to be sure you test the v1.2115 first, it might be the reason why you do not see the images.

**Comment by rtm729** [comment]
![image](https://github.com/twentyfortysix/uccnc_screenset_2046/assets/82761847/57244aaa-d9ed-4baa-bdd6-045d5b7ae936)
still having issue with 1.2115

**Comment by twentyfortysix** [comment]
Here is a temporary link to the BMP/Probe directory https://we.tl/t-k5esL1L8Y6
Although as I said, that this screen will be bit messy anyway. I have not touched this and I remember that there were quite weird looking buttons even on my machine, that I'm not on now, and will not be for a while still.
That is a part that would need some extra love. As I do not use this kind of probe, I have not paid too much attention to it .)

_(The UCCNC interface is quite hell, all texts but the dynamic values are as background image and everything is so skewed .. fortunately it is editable, but even that does not solve the issue, the GUI is just not well designed.)_
