### ISSUE TITLE
Stepcraft Q.408 Compatibility - Reset Logic Stuck

### ISSUE THREAD

**Issue by joshleong** [twentyfortysix/uccnc_screenset_2046#4]
SSF File:
https://drive.google.com/file/d/1uiL7PsaAvhECuVlnKH3F8RiCiE5MCuBW/view?usp=drive_link

2046.ssf file uploaded and working, but reset logic is stuck, new screen set does not connect with Q.408.

**Comment by twentyfortysix** [comment]
Hi @joshleong ,
i need the access to the ssf.. the ssf that i need is the one that is installed along the Q version when you installed the uccnc from the usb stick, in other words the original not mine ;) (just wanted to make sure we share what we need).
Can you make s screenshot of the diagnostic page as well?

in the meantime, I feel like the problem might be my Profile Profiles/Stepcraft_2046.pro ~coz my machine is twice bigger than yours and~ I feel like the machine wanted to home to a position that your is not able to. Try to reset the offsets.
As I believe that the reset button is universal. Send me the original Profile as well. I just feel you cannot reset as the machine tries to reset out off limits which are part of the offset definition in the Profile file that I shared along my color settings and stuff.

https://github.com/twentyfortysix/uccnc_screenset_2046/blob/main/UCCNC/Profiles/Stepcraft_2046.pro
see the Homingvalue=744 and Offests are set to 744 as well..

You might use the original Sceenset, make a copy , rename it to your liking and change the value to mainscreenfilename=Stepcraft_2046
That way your initial setup should stay and only load my screenset. Then you load the program change the profile to a new one you just made, it will restart the UCCNC, and you should be fine, I believe.

**Comment by joshleong** [comment]
Ok added you as an editor, I guess I can't attach the SSF to Github. I'll debug with your suggestion tomorrow morning when I'm back in the lab. Drop by if you are ever in Oahu, Hawaii!

**Comment by twentyfortysix** [comment]
I see no issues, which does not mean there are any.
Try the profile substitution.

_(btw "Hawaii" is synonym of "life at ease" in our part of the globe)_

**Comment by joshleong** [comment]
I tried what you suggested and it worked, I just changed the profile value to load your screenset!

Stepcraft_Q408.pro
https://gist.github.com/joshleong/0e0ff64e51a2439445c1781daac93582

Stepcraft_Q408_CE.pro
https://gist.github.com/joshleong/0440ede4922ba3da5eb503d05967e6c2

Here are my old .pro files for reference though.

**Comment by twentyfortysix** [comment]
Awesome.. I'll look at it and use the file for other people if you are ok with it.
I also tried again the new UCCNC version and it worked this time.. meaning I'm gonna make an update if the screenset within few months.. 

Great that it works.. some screens other that run and toolpaths will be bit of a mess, be aware for it.
